# GitHub Actions Workflow für Continuous Integration
#
# Dieser Workflow wird bei jedem Push und Pull Request ausgeführt.
# Er installiert die Projektabhängigkeiten und führt die gesamte Test-Suite aus,
# um die Code-Qualität und Stabilität sicherzustellen.

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Code auschecken
      uses: actions/checkout@v4

    - name: Python 3.11 einrichten
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Abhängigkeiten installieren
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Tests ausführen (mit virtuellem Display für Tkinter)
      run: |
        sudo apt-get update && sudo apt-get install -y xvfb
        xvfb-run python3 -m unittest discover -s tests