[pytest]
markers =
    db: tests that require a live database connection (PostgreSQL).
    alembic_migrations: tests specifically for database migration integrity.
    alembic: general alembic related tests.