# Dieser Workflow führt die Tests auf verschiedenen Betriebssystemen und Python-Versionen aus.
# Er nutzt den wiederverwendbaren Workflow, um Code-Duplizierung zu vermeiden.
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  call-reusable-test-workflow:
    uses: ./.github/workflows/reusable-test-workflow.yml
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.10', '3.11', '3.12']
        # Schließe inkompatible Kombinationen aus, falls nötig
        # exclude:
        #   - os: macos-latest
        #     python-version: '3.9'

    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
      # container-image wird nicht übergeben, da wir auf dem Host-System testen