name: Create Release

on:
  push:
    tags:
      - "v*.*.*" # Löst den Workflow aus, wenn ein Tag wie v1.2.3 gepusht wird

jobs:
  build-release:
    name: Build for ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: 1. Checkout code
        uses: actions/checkout@v4

      - name: 2. Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: 3. Install System Dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-tk python3-pil.imagetk xvfb

      - name: 4. Install Python Dependencies
        run: |
          python -m pip install --upgrade pip wheel
          # Für moderne Linux-Runner, die PEP 668 durchsetzen,
          # müssen wir pip anweisen, die systemverwaltete Umgebung zu ignorieren.
          if [ "$RUNNER_OS" == "Linux" ]; then
            pip install -r requirements.txt -r requirements-dev.txt --break-system-packages
          else
            pip install -r requirements.txt -r requirements-dev.txt
          fi
          pip install pyinstaller

      - name: 5. Run Build Script
        # Das build.py Skript führt Tests aus, baut die App und erstellt das ZIP-Archiv
        run: python build.py

      - name: 6. Upload Release Assets
        uses: actions/upload-artifact@v4
        if: runner.os == 'Windows'
        with:
          name: release-asset-windows-installer
          path: |
            DartCounter_*.zip

      - name: 6. Upload Release Assets (Linux/macOS)
        uses: actions/upload-artifact@v4
        if: runner.os != 'Windows'
        with:
          name: release-asset-${{ matrix.os }}
          path: DartCounter_*.zip

  build-installer:
    name: Build Windows Installer
    needs: build-release # Startet, wenn der Windows-Build fertig ist
    runs-on: windows-latest

    steps:
      - name: 1. Checkout code
        uses: actions/checkout@v4

      - name: 2. Download Windows build artifact
        uses: actions/download-artifact@v4
        with:
          name: release-asset-windows-installer
          path: release

      - name: 3. Unzip build artifact
        run: |
          Expand-Archive -Path release/DartCounter_*.zip -DestinationPath .

      - name: 4. Set up Inno Setup
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2

      - name: 5. Prepare Installer Script
        shell: pwsh
        run: |
          $version = "${{ github.ref_name }}".Substring(1)
          $sourceDir = "DartCounter_Windows_v" + $version
          $issFile = "installer/create_installer.iss"
          (Get-Content $issFile -Raw) -replace '__APP_VERSION__', $version -replace '__SOURCE_DIR__', $sourceDir | Set-Content -Path $issFile
          echo "Installer script for v$version prepared."

      - name: 6. Compile Windows Installer
        run: iscc.exe installer/create_installer.iss

      - name: 7. Upload Installer as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: installer/Output/DartCounter_Setup.exe

  publish-release:
    name: Publish GitHub Release
    needs: [build-release, build-installer]
    runs-on: ubuntu-latest
    permissions:
      contents: write # Notwendig, um Assets zu einem Release hinzuzufügen

    steps:
      - name: 1. Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-assets # Lädt alle Artefakte in diesen Ordner

      - name: 3. Extract Release Notes from CHANGELOG.md
        id: extract_release_notes
        run: |
          VERSION_TAG=${{ github.ref_name }}
          NOTES=$(awk -v tag="## [${VERSION_TAG#v}]" '
            $0 ~ tag {f=1; next}
            f && /^---/ {exit}
            f {print}
          ' CHANGELOG.md)
          echo "notes<<EOF" >> $GITHUB_OUTPUT
          echo "$NOTES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: 4. Create Release and Upload All Assets
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          body: ${{ steps.extract_release_notes.outputs.notes }}
          draft: false
          prerelease: false
          files: |
            release-assets/release-asset-ubuntu-latest/DartCounter_*.zip
            release-assets/release-asset-macos-latest/DartCounter_*.zip
            release-assets/windows-installer/DartCounter_Setup.exe
