# Dieser Workflow ist als wiederverwendbar konzipiert und wird von anderen Workflows aufgerufen.
# Er enthält die gesamte Kernlogik für das Testen der Anwendung.
name: Reusable Test Workflow

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      python-version:
        required: true
        type: string
      container-image:
        required: false
        type: string

jobs:
  test:
    name: Test on ${{ inputs.os }} with Python ${{ inputs.python-version }}
    runs-on: ${{ inputs.os }}
    container:
      image: ${{ inputs.container-image }}

    steps:
      - name: 1. Install System Prerequisites (for container)
        if: ${{ inputs.container-image }}
        run: |
          apt-get update
          apt-get install -y git python3 python3-pip python3-tk python3-pil.imagetk xvfb

      - name: 2. Checkout Code
        uses: actions/checkout@v4

      - name: 3. Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: 4. Install System Dependencies (for Linux runner)
        if: runner.os == 'Linux' && !inputs.container-image
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-tk python3-pil.imagetk xvfb

      - name: 4. Install System Dependencies (for macOS runner)
        if: runner.os == 'macOS'
        run: |
          brew install --cask xquartz
          brew install xvfb-run

      - name: 5. Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt

      - name: 6. Run Tests with Virtual Display (Linux/macOS)
        if: runner.os == 'Linux' || runner.os == 'macOS'
        run: xvfb-run python -m pytest
      - name: 6. Run Tests (Windows)
        if: runner.os == 'Windows'
        run: python -m pytest