name: Test on Debian Trixie

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-on-trixie:
    name: Run Tests on Debian Trixie (testing)
    runs-on: ubuntu-latest
    container:
      image: debian:trixie

    steps:
    - name: 1. Install System Prerequisites
      run: |
        apt-get update
        # git wird für die checkout-Action benötigt
        # python3-tk, python3-pil.imagetk und xvfb sind für die GUI-Tests erforderlich
        apt-get install -y git python3 python3-pip python3-tk python3-pil.imagetk xvfb

    - name: 2. Checkout Code
      uses: actions/checkout@v4

    - name: 3. Install Python Dependencies
      run: |
        python3 -m pip install --upgrade pip
        # Installiert alle notwendigen Pakete für die Ausführung und Entwicklung
        pip3 install -r requirements.txt -r requirements-dev.txt

    - name: 4. Run Tests with Virtual Display
      # Führt die pytest-Suite in einer virtuellen "Kopf-losen" Umgebung aus.
      # Die Optionen werden aus der pytest.ini geladen.
      run: xvfb-run python3 -m pytest