name: Test on Debian Trixie

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-trixie-tests:
    uses: ./.github/workflows/reusable-test-workflow.yml
    with:
      os: ubuntu-latest
      python-version: '3.11' # Die Python-Version, die im Container verwendet werden soll
      container-image: debian:trixie